#Configuración del puerto del servidor, en este caso 8080 por defecto
server:
  port: 8080  #Puerto
  host: "0.0.0.0"   #En cualquier lugar

#Configuración de permisos sobre quien puede o no usar el servidor, en este caso, la dirección de vite
cors:
  paths:
      - "path-pattern": "*"   #Acceso a todas las direcciones
        "allow-origins": ["http://localhost:5173"]   #Origen permitido
        "allow-methods": ["GET","POST","PUT","DELETE","OPTIONS"]  #Métodos permitidos
        "allow-headers": ["Content-Type"]  #Tipo de contenido permitido

#Configuración de la base de datos
db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:5432/progweb"  #Dirección a la base de datos, en este caso postgres
    username: "postgres"                             #Usuario de la base de datos
    password: "password"                             #Contraseña de la base de datos, cambiar si es necesario
    driverClassName: "org.postgresql.Driver"         #Nombre del driver a utilizar

  #Sentencias SQL utilizadas para el CRUD de cada entidad incluyendo la creación de cada tabla el cual se ejecuta al iniciar el programa
  statements:

    create-users: "CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name VARCHAR(50), username VARCHAR(50), email VARCHAR(15), address_Street VARCHAR(50),address_Suite VARCHAR(50), address_City VARCHAR(15),address_ZipCode VARCHAR(10), address_Geo_Lat VARCHAR(10), address_Geo_Lng VARCHAR(10), phone VARCHAR(10), website VARCHAR(50),company_Name VARCHAR(50),company_Catch_Phrase VARCHAR(50), company_Bs VARCHAR(50))"
    create-albums: "CREATE TABLE IF NOT EXISTS albums (id SERIAL PRIMARY KEY, title VARCHAR(50),user_id INT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)"
    create-photos: "CREATE TABLE IF NOT EXISTS photos (id SERIAL PRIMARY KEY, title VARCHAR(50),url VARCHAR(50),thumbnail_url VARCHAR(50),album_id INT NOT NULL, FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE)"
    create-posts: "CREATE  TABLE IF NOT EXISTS posts (id SERIAL PRIMARY KEY, title VARCHAR(50), user_id INT NOT NULL, body VARCHAR(50), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)"
    create-comments: "CREATE  TABLE IF NOT EXISTS comments (id SERIAL PRIMARY KEY, name VARCHAR(50), email VARCHAR(50), post_id INT NOT NULL, body VARCHAR(50), FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE)"
    create-todos: "CREATE TABLE IF NOT EXISTS todos (id SERIAL PRIMARY KEY, title VARCHAR(50),completed BOOLEAN,user_id INT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)"

    select-users: "SELECT * FROM users"
    select-todos: "SELECT * FROM todos"
    select-albums: "SELECT * FROM albums"
    select-photos: "SELECT * FROM photos"
    select-comments: "SELECT * FROM comments"
    select-posts: "SELECT * FROM posts"

    select-userId: "SELECT * FROM users WHERE id = :id"
    select-todoId: "SELECT * FROM todos WHERE id = :id"
    select-albumId: "SELECT * FROM albums WHERE id = :id"
    select-photoId: "SELECT * FROM photos WHERE id = :id"
    select-commentId: "SELECT * FROM comments WHERE id = :id"
    select-postId: "SELECT * FROM posts WHERE id = :id"

    insert-user: "INSERT INTO users (name, username, email, address_street, address_suite, address_city, address_zipcode, address_geo_lat, address_geo_lng, phone, website, company_name, company_catch_phrase, company_bs) VALUES (:name, :username, :email, :addressStreet, :addressSuite, :addressCity, :addressZipcode, :addressGeoLat, :addressGeoLng, :phone, :website, :companyName, :companyCatchPhrase, :companyBs) RETURNING id"
    insert-todo: "INSERT INTO todos (title, completed, user_id) VALUES (:title, :completed, :user_id) RETURNING id"
    insert-album: "INSERT INTO albums (title, user_id) VALUES (:title, :user_id) RETURNING id"
    insert-photo: "INSERT INTO photos (title, url, thumbnail_url, album_id) VALUES (:title, :url, :thumbnail_url, :album_id) RETURNING id"
    insert-comment: "INSERT INTO comments (name, email, post_id, body) VALUES (:name, :email, :post_id, :body) RETURNING id"
    insert-post: "INSERT INTO posts (title, user_id, body) VALUES (:title, :user_id, :body) RETURNING id"

    update-user: "UPDATE users SET name = :name, username = :username, email = :email, address_street = :addressStreet, address_suite = :addressSuite, address_city = :addressCity, address_zipcode = :addressZipcode, address_geo_lat = :addressGeoLat, address_geo_lng = :addressGeoLng, phone = :phone, website = :website, company_name = :companyName, company_catch_phrase = :companyCatchPhrase, company_bs = :companyBs WHERE id = :id"
    update-todo: "UPDATE todos SET title = :title, completed = :completed WHERE id = :id"
    update-album: "UPDATE albums SET title = :title WHERE id = :id"
    update-photo: "UPDATE photos SET title = :title, url = :url, thumbnail_url = :thumbnail_url WHERE id = :id"
    update-comment: "UPDATE comments SET name = :name, email = :email, body = :body WHERE id = :id"
    update-post: "UPDATE posts SET title = :title, body = :body WHERE id = :id"

    delete-user: "DELETE FROM users WHERE id = :id"
    delete-todo: "DELETE FROM todos WHERE id = :id"
    delete-album: "DELETE FROM albums WHERE id = :id"
    delete-photo: "DELETE FROM photos WHERE id = :id"
    delete-comment: "DELETE FROM comments WHERE id = :id"
    delete-post: "DELETE FROM posts WHERE id = :id"